name: Docker Image CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
env:
  #REGISTRY_NAME: parstat
  APP_NAME: iais-structural-api

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and publish a Docker image for ghcr ${{ env.APP_NAME }}
      uses: macbre/push-to-ghcr@master
      with:
        image_name: statisticamd-dev/${{ env.APP_NAME }}  # it will be lowercased internally
        github_token: ${{ secrets.GITHUB_TOKEN }}
        dockerfile: Parstat.StructuralMetadata/Presentation/Presentation.WebApi/Dockerfile
        image_tag: latest
        #login-server: ghcr.io/statisticamd-dev/
        #username: developer
        #password: ${{ secrets.REGISTRY_PASSWORD }}
    #- name: Build the Docker image
      #run: docker build Parstat.StructuralMetadata/ --file Parstat.StructuralMetadata/Presentation/Presentation.WebApi/Dockerfile  --tag ghcr.io/statisticamd-dev/${{ env.APP_NAME }}:latest
    #- name: Push Image to Docker
    #  run: docker push ghcr.io/statisticamd-dev/${{ env.APP_NAME }}:latest
        run: echo ${{ secrets.GITHUB_TOKEN }}
    - name: Push to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_NAME }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: cd iais && docker stack deploy --compose-file docker-compose.yml --with-registry-auth iais
